# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - trip2mk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://trip2mkimages.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1677d4df686c459ea7c356e754382d41 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_27adb5fdca61445294b21c8e27ddd0b7 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: trip2mkimages.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1677d4df686c459ea7c356e754382d41 }}/trip2mk:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'trip2mk'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a7b50bb09b594fbf8029520a53ea490a }}
        images: 'trip2mkimages.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1677d4df686c459ea7c356e754382d41 }}/trip2mk:${{ github.sha }}'